config/routes.rb
Rails.application.routes.draw do

  mount_devise_token_auth_for 'User', at: 'users', controllers: {
      sessions:  'overrides/sessions',
      registrations: 'overrides/registrations'
  }

  root 'pages#home'

  resources :articles, except: [:new, :edit, :destroy] do
    collection do
      get 'queue'
      get 'favorites'
    end
  end

  get '/users/:id/submit_articles', to: "articles#submit_articles"

  get '/pages/home', to: 'pages#home', as: :before_start
  get '/pages/user', to: 'pages#user', as: :user_api
  get '/pages/article', to: 'pages#article', as: :article_api

  get 'users/:id/information', to: 'users#show', as: :user_info

  post 'users/oauth/facebook', to: "users#fb_oauth", as: :fb_oauth

  post 'users/oauth/google', to: "users#google_oauth", as: :google_oauth

  post 'articles/:id/like', to: "favorites#like", as: :like
  post 'articles/:id/unlike', to: "favorites#unlike", as: :unlike
  post 'articles/:id/vote', to: "votes#create", as: :vote

end

app/views/shared/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "ColinApiCore" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>

app/views/shared/_sidebar.html.erb
<ol>
  <li>
    <%= link_to 'Before Start', before_start_path %>
  </li>

  <li>
    <%= link_to 'Account', user_api_path %>
  </li>

  <li>
    <%= link_to 'Article', article_api_path %>
  </li>
</ol>